//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOHBackend.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FOHBackend.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to document.getElementById(&quot;loginForm&quot;).elements[&quot;txtEmailAdd&quot;].value = &quot;{0}&quot;;            
        ///document.getElementById(&quot;loginForm&quot;).elements[&quot;txtPassword&quot;].value = &quot;{1}&quot;;            
        ///document.getElementById(&quot;loginForm&quot;).submit();
        ///.
        /// </summary>
        public static string autologin {
            get {
                return ResourceManager.GetString("autologin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to document.getElementById(&quot;login_form&quot;).elements[&quot;user&quot;].value = &quot;{0}&quot;;            
        ///document.getElementById(&quot;login_form&quot;).elements[&quot;pass&quot;].value = &quot;{1}&quot;;            
        ///document.getElementById(&quot;login_form&quot;).submit();
        ///.
        /// </summary>
        public static string autologinemail {
            get {
                return ResourceManager.GetString("autologinemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function () {{
        ///        {0}
        ///        window[&apos;btnExport&apos;].DoClick();
        ///        return 0;
        ///}})();.
        /// </summary>
        public static string exportCommand {
            get {
                return ResourceManager.GetString("exportCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Basic Settings
        ///window[&apos;chkAllBooks&apos;].SetChecked(true);
        ///window[&apos;ctl00_ContentPlaceHolder1_CallbackPanelLabel_cblIncludeHeader&apos;].SetChecked(false);
        ///window[&apos;ctl00_ContentPlaceHolder1_CallbackPanelLabel_cblGroupDuplicatedDetails&apos;].SetChecked(false);
        ///window[&apos;chkExcludeBOFQuickSale&apos;].SetChecked(false);
        ///window[&apos;chkIncludeRefundedTickets&apos;].SetChecked(false);
        ///
        ///// Event Details            
        ///document.getElementById(&quot;ctl00_ContentPlaceHolder1_CallbackPanelLabel_cblEventDetails_0&quot;).checked = true;
        ///document.ge [rest of string was truncated]&quot;;.
        /// </summary>
        public static string exportSettings {
            get {
                return ResourceManager.GetString("exportSettings", resourceCulture);
            }
        }
    }
}
